# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r echo=TRUE}
myurl<-("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip")
download.file(myurl, "activity.zip",method="curl")
unzip("activity.zip")
raw_df<-read.csv("activity.csv")
```



## What is mean total number of steps taken per day?

```{r echo = TRUE}
library(ggplot2)
daily_sum<-setNames(aggregate(raw_df$steps,list(raw_df$date),sum),c("date","steps"))
m <- ggplot(daily_sum, aes(x=steps))

m + geom_histogram(colour="White",fill = "steelblue",binwidth=1000)+scale_y_continuous(breaks=seq(0,10))+
  ylab("Number of Days")+
  xlab("Steps Taken")+
  ggtitle("Histogram of total daily steps\n2012-10-01 to 2012-11-30")+
  theme(plot.title = element_text(lineheight=1, face="bold"))

mean(daily_sum$steps,na.rm=TRUE)
median(daily_sum$steps,na.rm=TRUE)


```


## What is the average daily activity pattern?

```{r echo=TRUE}
avg_steps_per_interval<-setNames(aggregate(raw_df$steps,list(raw_df$interval),
                                           mean,na.rm=TRUE),c("interval","steps"))

pretty_labels<-paste(substr(sprintf("%04d",seq(0,2400,by=300)),1,2),":",substr(sprintf("%04d",seq(0,2400,by=300)),3,5),sep="")


ggplot(data=avg_steps_per_interval, aes(x=interval, y=steps)) + geom_line() + 
  scale_x_discrete(breaks=seq(0,2400,by=300),
  labels=pretty_labels)+
  ylab("Average Steps Taken")+
  xlab("Time of Day")+
  ggtitle("Average total steps at 5 minute intervals throughout day\n
          2012-10-01 to 2012-11-30")+
  theme(plot.title = element_text(lineheight=1, face="bold"))
  

max_steps_time<-avg_steps_per_interval$interval[which.max(avg_steps_per_interval$steps)]
max_steps_time                                 
                                 
```


## Imputing missing values
```{r echo=TRUE}
table(aggregate(raw_df$steps,list(raw_df$date),function(x) sum( !is.na(x) )))
raw_df$day_of_week<-weekdays(as.POSIXlt(raw_df$date))
library(plyr)
raw_df$id<-as.numeric(rownames(raw_df))
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
fill_means_for_day <- ddply(raw_df, .(day_of_week,interval), transform, steps = impute.mean(steps))
  

fill_means_for_day<-fill_means_for_day[order(fill_means_for_day$id), ] 
imputed_sums<-setNames(aggregate(fill_means_for_day$steps,list(raw_df$date),sum),
                         c("date","steps"))
m <- ggplot(imputed_sums, aes(x=steps))
m + geom_histogram(colour="White",fill = "blue",binwidth=1000)+scale_y_continuous(breaks=seq(0,10))+
  ylab("Number of Days")+
  xlab("Steps Taken")+annotate("text", x = 18000, y = 8, label = "NA values replaced\nwith weekday interval\n average")+
  ggtitle("Histogram of total daily steps\n2012-10-01 to 2012-11-30")+
  theme(plot.title = element_text(lineheight=1, face="bold"))

mean(imputed_sums$steps)
median(imputed_sums$steps)

```



## Are there differences in activity patterns between weekdays and weekends?

```{r echo=TRUE}
fill_means_for_day$weekend<-ifelse(fill_means_for_day$day_of_week=="Saturday"|fill_means_for_day$day_of_week=="Sunday","Weekend","Weekday")


compare_days<-aggregate(fill_means_for_day$steps,list(fill_means_for_day$weekend,fill_means_for_day$interval),mean)
m <- ggplot(compare_days, aes(x=Group.2,y=x))
m+geom_line(color="steelblue",size=1.1)+facet_grid(Group.1~.)+
ylab("Average Number of Steps")+
xlab("Time of day")+
  facet_grid(Group.1~.)+
  scale_x_discrete(breaks=seq(0,2400,by=300),labels=pretty_labels)+
  ggtitle("Comparision of Weekend\n vs Weekday steps taken\n2012-10-01 to 2012-11-30")+
  theme(plot.title = element_text(lineheight=1, face="bold"))

```

